import type {
  BlockDefinition,
  BlockKind,
  StrategyTemplate,
} from "@/types/block";
import { ARC_LOGO_SRC, USDC_LOGO_SRC } from "./assets";

export const BLOCK_KINDS: BlockKind[] = [
  "trigger",
  "approve",
  "deposit",
  "swap",
  "yield",
  "harvest",
  "bridge",
  "withdraw",
  "condition",
  "alert",
];

export const BLOCK_CATALOG: Record<BlockKind, BlockDefinition> = {
  trigger: {
    kind: "trigger",
    label: "Start",
    group: "Trigger",
    description: "Kick off the strategy on a schedule or on demand.",
    icon: "bolt",
    logoImages: [
      { src: USDC_LOGO_SRC, alt: "USDC" },
      { src: ARC_LOGO_SRC, alt: "Arc" },
    ],
    subtitle: "Every 24 hours",
  },
  approve: {
    kind: "approve",
    label: "Approve Token",
    group: "Setup",
    description: "Grant a protocol permission to move an asset.",
    icon: "approve",
    logo: "ethereum",
    subtitle: "ERC-20 allowance",
  },
  deposit: {
    kind: "deposit",
    label: "Deposit",
    group: "Liquidity",
    description: "Supply an asset into a lending pool or vault.",
    icon: "deposit",
    logo: "aave",
    subtitle: "Aave V3 Pool",
  },
  swap: {
    kind: "swap",
    label: "Swap Token",
    group: "Trading",
    description: "Route a trade through the best available pool.",
    icon: "swap",
    logo: "uniswap",
    subtitle: "Uniswap V3",
  },
  yield: {
    kind: "yield",
    label: "Yield Farm",
    group: "Yield",
    description: "Stake an LP position and auto-compound rewards.",
    icon: "yield",
    logo: "curve",
    subtitle: "Curve Finance",
  },
  harvest: {
    kind: "harvest",
    label: "Harvest Rewards",
    group: "Yield",
    description: "Claim accrued incentives once they clear a threshold.",
    icon: "harvest",
    logo: "curve",
    subtitle: "Curve Gauge",
  },
  bridge: {
    kind: "bridge",
    label: "Bridge Asset",
    group: "Routing",
    description: "Move an asset across chains before the next step.",
    icon: "bridge",
    logo: "chainlink",
    subtitle: "Chainlink CCIP",
  },
  withdraw: {
    kind: "withdraw",
    label: "Withdraw",
    group: "Liquidity",
    description: "Pull a position back out of a pool or vault.",
    icon: "withdraw",
    logo: "aave",
    subtitle: "Aave V3 Pool",
  },
  condition: {
    kind: "condition",
    label: "Condition",
    group: "Logic",
    description:
      "Read a price feed and end the run early when it crosses a bound.",
    icon: "condition",
    logo: "chainlink",
    subtitle: "Chainlink Data Feed",
  },
  alert: {
    kind: "alert",
    label: "Alert",
    group: "Monitoring",
    description: "Notify a channel when a step fails or drifts.",
    icon: "alert",
    logo: "telegram",
    subtitle: "Telegram",
  },
};

export const STRATEGY_TEMPLATES: StrategyTemplate[] = [
  {
    id: "stable-auto-compound",
    name: "Stablecoin auto-compound",
    description: "Supply USDC, farm the pair and reinvest rewards daily.",
    tokens: ["usdc"],
    kinds: ["approve", "deposit", "yield", "harvest"],
  },
  {
    id: "weekly-dca",
    name: "Weekly ETH accumulation",
    description: "Swap a fixed amount into ETH every week and report it.",
    tokens: ["usdc", "ethereum"],
    kinds: ["trigger", "swap", "alert"],
  },
  {
    id: "cross-chain-yield",
    name: "Cross-chain yield hop",
    description: "Bridge idle stables to Arc, then park them in a vault.",
    tokens: ["usdc"],
    kinds: ["bridge", "approve", "deposit", "yield"],
  },
  {
    id: "guarded-exit",
    name: "Guarded farm exit",
    description: "Watch a price feed and unwind the position when it drops.",
    tokens: ["usdc", "ethereum"],
    kinds: ["condition", "harvest", "withdraw", "alert"],
  },
  {
    id: "idle-cash-sweep",
    name: "Idle cash sweep",
    description: "Sweep leftover USDC into the lending pool every night.",
    tokens: ["usdc"],
    kinds: ["trigger", "approve", "deposit"],
  },
  {
    id: "reward-compounding-loop",
    name: "Reward compounding loop",
    description: "Claim rewards, swap them back to the pair and restake.",
    tokens: ["usdc", "ethereum"],
    kinds: ["harvest", "swap", "deposit", "yield"],
  },
  {
    id: "risk-off-unwind",
    name: "Risk-off unwind",
    description: "Exit the farm, bridge home and report when a guard trips.",
    tokens: ["usdc"],
    kinds: ["condition", "withdraw", "bridge", "alert"],
  },
  {
    id: "lp-bootstrap",
    name: "LP bootstrap",
    description: "Split a stable balance into a pair and stake the position.",
    tokens: ["usdc", "ethereum"],
    kinds: ["approve", "swap", "yield"],
  },
];
